import { getCoverageForPostcode, type CoverageResult } from "@/lib/postcode-coverage";

export type ServiceValue =
  | "cleaning"
  | "pest-control"
  | "handyman"
  | "furniture-assembly"
  | "waste-removal"
  | "garden-maintenance";

export type PropertyTypeValue = "flat" | "terraced" | "semi-detached" | "detached" | "commercial";
export type JobSizeValue = "small" | "standard" | "large";
export type UrgencyValue = "planned" | "priority" | "same-day";
export type CleaningConditionValue = "light" | "standard" | "heavy" | "very-heavy";
export type RecurringFrequencyValue = "one-off" | "weekly" | "fortnightly" | "monthly";

export type AddOnDefinition = {
  value: string;
  label: string;
  amount: number;
};

export type JobTypeDefinition = {
  value: string;
  service: ServiceValue;
  subcategory: string;
  label: string;
  strapline: string;
  bookingMode: "fixed" | "estimate" | "inspection";
  leadTimeLabel: string;
  startingPrice: number;
  bookingFee: number;
  basePrice: number;
  providerPayoutRatio: number;
  durationHours: Record<JobSizeValue, number>;
  sizeOptions: Array<{ value: JobSizeValue; label: string; priceDelta: number }>;
  addOns: AddOnDefinition[];
  propertyTypes: PropertyTypeValue[];
  providerTags: string[];
};

export type ServiceDefinition = {
  value: ServiceValue;
  label: string;
  strapline: string;
  subcategories: Array<{ value: string; label: string }>;
};

export const propertyTypeOptions: Array<{ value: PropertyTypeValue; label: string; priceDelta: number }> = [
  { value: "flat", label: "Flat / apartment", priceDelta: 0 },
  { value: "terraced", label: "Terraced house", priceDelta: 10 },
  { value: "semi-detached", label: "Semi-detached house", priceDelta: 18 },
  { value: "detached", label: "Detached house", priceDelta: 28 },
  { value: "commercial", label: "Commercial premises", priceDelta: 35 },
];

export const urgencyOptions: Array<{ value: UrgencyValue; label: string; priceDelta: number }> = [
  { value: "planned", label: "Planned booking", priceDelta: 0 },
  { value: "priority", label: "Priority within 24 hours", priceDelta: 24 },
  { value: "same-day", label: "Same-day response", priceDelta: 45 },
];

export const cleaningConditionOptions: Array<{ value: CleaningConditionValue; label: string; multiplier: number }> = [
  { value: "light", label: "Light", multiplier: 0.95 },
  { value: "standard", label: "Standard", multiplier: 1 },
  { value: "heavy", label: "Heavy", multiplier: 1.18 },
  { value: "very-heavy", label: "Very heavy", multiplier: 1.38 },
];

export const recurringFrequencyOptions: Array<{ value: RecurringFrequencyValue; label: string; multiplier: number }> = [
  { value: "one-off", label: "One-off", multiplier: 1 },
  { value: "weekly", label: "Weekly", multiplier: 0.9 },
  { value: "fortnightly", label: "Fortnightly", multiplier: 0.95 },
  { value: "monthly", label: "Monthly", multiplier: 1 },
];

export const serviceCatalog: ServiceDefinition[] = [
  {
    value: "cleaning",
    label: "Cleaning",
    strapline: "Bookable residential and property cleaning jobs with clear scope.",
    subcategories: [
      { value: "home-cleaning", label: "Home cleaning" },
      { value: "tenancy-cleaning", label: "Tenancy & move cleaning" },
      { value: "specialist-cleaning", label: "Specialist cleaning" },
      { value: "appliance-cleaning", label: "Appliance cleaning" },
      { value: "window-cleaning", label: "Window cleaning" },
      { value: "room-deep-cleans", label: "Room deep cleans" },
    ],
  },
  {
    value: "pest-control",
    label: "Pest control",
    strapline: "Inspection-led pest treatments and same-day emergency response.",
    subcategories: [
      { value: "rodents", label: "Rodents" },
      { value: "insects", label: "Insects" },
      { value: "surveys", label: "Inspections & reports" },
      { value: "proofing", label: "Proofing & follow-up" },
    ],
  },
  {
    value: "handyman",
    label: "Handyman",
    strapline: "Detailed task-based handyman jobs with capability-led dispatch.",
    subcategories: [
      { value: "mounting-hanging", label: "Mounting & hanging" },
      { value: "repairs", label: "Minor repairs" },
      { value: "fixtures-fittings", label: "Fixtures & fittings" },
      { value: "moving-adjustments", label: "Moving & adjustments" },
      { value: "electrical-light", label: "Light electrical" },
    ],
  },
  {
    value: "furniture-assembly",
    label: "Furniture assembly",
    strapline: "Assembly, disassembly, anchoring, and room setup tasks.",
    subcategories: [
      { value: "bedroom", label: "Bedroom furniture" },
      { value: "living-office", label: "Living room & office" },
      { value: "extras", label: "Disassembly & anchoring" },
      { value: "dining-seating", label: "Dining & seating" },
      { value: "special-ranges", label: "Special ranges" },
    ],
  },
  {
    value: "waste-removal",
    label: "Waste removal",
    strapline: "Photo-friendly removal jobs for household, garden, and property waste.",
    subcategories: [
      { value: "household", label: "Household waste" },
      { value: "bulky-items", label: "Bulky items" },
      { value: "clearances", label: "Clearances" },
      { value: "special-disposal", label: "Special disposal" },
    ],
  },
  {
    value: "garden-maintenance",
    label: "Garden maintenance",
    strapline: "Routine garden work, tidy-ups, and seasonal outdoor jobs.",
    subcategories: [
      { value: "routine", label: "Routine maintenance" },
      { value: "cutting-trimming", label: "Cutting & trimming" },
      { value: "seasonal", label: "Seasonal tidy-ups" },
      { value: "washing-finishing", label: "Washing & finishing" },
    ],
  },
];

export const jobTypeCatalog: JobTypeDefinition[] = [
  {
    value: "regular-home-cleaning",
    service: "cleaning",
    subcategory: "home-cleaning",
    label: "Regular home cleaning",
    strapline: "Routine weekly, fortnightly, or one-off home cleaning visits.",
    bookingMode: "estimate",
    leadTimeLabel: "Scheduled weekday and weekend cleaning slots.",
    startingPrice: 58,
    bookingFee: 12,
    basePrice: 48,
    providerPayoutRatio: 0.68,
    durationHours: { small: 2, standard: 3, large: 4.5 },
    sizeOptions: [
      { value: "small", label: "Studio / 1 bed", priceDelta: 0 },
      { value: "standard", label: "2 to 3 bedroom home", priceDelta: 28 },
      { value: "large", label: "4 plus bedroom home", priceDelta: 62 },
    ],
    addOns: [
      { value: "oven-clean", label: "Oven clean", amount: 20 },
      { value: "inside-windows", label: "Inside windows", amount: 20 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "domestic-cleaning"],
  },
  {
    value: "end-of-tenancy-cleaning",
    service: "cleaning",
    subcategory: "tenancy-cleaning",
    label: "End of tenancy cleaning",
    strapline: "Move-out deep cleaning for landlords, tenants, and agents.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with property size and handover timing.",
    startingPrice: 129,
    bookingFee: 19,
    basePrice: 112,
    providerPayoutRatio: 0.67,
    durationHours: { small: 3, standard: 5, large: 7 },
    sizeOptions: [
      { value: "small", label: "Studio / 1 bed", priceDelta: 0 },
      { value: "standard", label: "2 to 3 bedroom property", priceDelta: 74 },
      { value: "large", label: "4 plus bedroom property", priceDelta: 150 },
    ],
    addOns: [
      { value: "carpet-clean", label: "Carpet clean", amount: 45 },
      { value: "appliance-clean", label: "Fridge and oven deep clean", amount: 35 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "tenancy-cleaning"],
  },
  {
    value: "carpet-upholstery-cleaning",
    service: "cleaning",
    subcategory: "specialist-cleaning",
    label: "Carpet / upholstery cleaning",
    strapline: "Specialist fabric and carpet cleaning for homes and rentals.",
    bookingMode: "estimate",
    leadTimeLabel: "Bookable specialist cleaning windows.",
    startingPrice: 79,
    bookingFee: 15,
    basePrice: 66,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "One room or sofa", priceDelta: 0 },
      { value: "standard", label: "Two to three rooms", priceDelta: 34 },
      { value: "large", label: "Whole property / multiple items", priceDelta: 86 },
    ],
    addOns: [
      { value: "stain-treatment", label: "Stain treatment", amount: 18 },
      { value: "deodorising", label: "Deodorising", amount: 12 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["cleaning", "carpet-cleaning"],
  },
  {
    value: "rat-mouse-treatment",
    service: "pest-control",
    subcategory: "rodents",
    label: "Rat / mouse treatment",
    strapline: "Initial rodent control treatment for homes and small commercial sites.",
    bookingMode: "inspection",
    leadTimeLabel: "Same-day and next-day rodent response.",
    startingPrice: 129,
    bookingFee: 29,
    basePrice: 118,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Single room / trace signs", priceDelta: 0 },
      { value: "standard", label: "Standard home treatment", priceDelta: 42 },
      { value: "large", label: "Complex or repeat infestation", priceDelta: 95 },
    ],
    addOns: [
      { value: "written-report", label: "Written treatment report", amount: 22 },
      { value: "follow-up-visit", label: "Reserve follow-up visit", amount: 35 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "rodent-control"],
  },
  {
    value: "cockroach-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Cockroach treatment",
    strapline: "Kitchen and bathroom cockroach treatments with inspection notes.",
    bookingMode: "inspection",
    leadTimeLabel: "Priority insect treatment coverage across London.",
    startingPrice: 149,
    bookingFee: 29,
    basePrice: 136,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One affected area", priceDelta: 0 },
      { value: "standard", label: "Whole flat treatment", priceDelta: 48 },
      { value: "large", label: "Large or repeat outbreak", priceDelta: 102 },
    ],
    addOns: [
      { value: "written-report", label: "Written treatment report", amount: 22 },
      { value: "monitor-traps", label: "Monitoring trap pack", amount: 28 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "cockroach-treatment"],
  },
  {
    value: "wasp-nest-removal",
    service: "pest-control",
    subcategory: "insects",
    label: "Wasp nest removal",
    strapline: "Rapid wasp nest treatment for accessible residential and commercial sites.",
    bookingMode: "fixed",
    leadTimeLabel: "Fast same-day response for urgent nests.",
    startingPrice: 99,
    bookingFee: 25,
    basePrice: 88,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2 },
    sizeOptions: [
      { value: "small", label: "Single accessible nest", priceDelta: 0 },
      { value: "standard", label: "High access or awkward location", priceDelta: 30 },
      { value: "large", label: "Multiple nests or commercial site", priceDelta: 78 },
    ],
    addOns: [
      { value: "second-nest", label: "Second nest treatment", amount: 34 },
      { value: "written-report", label: "Insurance / landlord report", amount: 20 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "wasp-removal"],
  },
  {
    value: "pest-survey-report",
    service: "pest-control",
    subcategory: "surveys",
    label: "Pest inspection and report",
    strapline: "Inspection-only visit for landlords, buyers, and uncertain infestations.",
    bookingMode: "inspection",
    leadTimeLabel: "Bookable inspection slots with report add-ons.",
    startingPrice: 89,
    bookingFee: 25,
    basePrice: 76,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 2 },
    sizeOptions: [
      { value: "small", label: "Inspection only", priceDelta: 0 },
      { value: "standard", label: "Inspection plus treatment plan", priceDelta: 22 },
      { value: "large", label: "Commercial or multi-unit survey", priceDelta: 64 },
    ],
    addOns: [
      { value: "written-report", label: "Detailed written report", amount: 28 },
      { value: "photo-evidence", label: "Photo evidence pack", amount: 18 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "inspection"],
  },
  {
    value: "tv-mounting",
    service: "handyman",
    subcategory: "mounting-hanging",
    label: "TV mounting",
    strapline: "Wall mounting for TVs with bracket, cable, and wall-type considerations.",
    bookingMode: "fixed",
    leadTimeLabel: "Bookable in standard provider time windows.",
    startingPrice: 89,
    bookingFee: 19,
    basePrice: 79,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Up to 42 inch", priceDelta: 0 },
      { value: "standard", label: "43 to 64 inch", priceDelta: 20 },
      { value: "large", label: "65 inch plus / specialist mount", priceDelta: 52 },
    ],
    addOns: [
      { value: "cable-concealment", label: "Cable concealment", amount: 35 },
      { value: "bracket-supply", label: "Provider supplies bracket", amount: 28 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "tv-mounting", "drilling"],
  },
  {
    value: "mirror-picture-hanging",
    service: "handyman",
    subcategory: "mounting-hanging",
    label: "Mirror / picture hanging",
    strapline: "Precise hanging for mirrors, picture sets, and wall décor.",
    bookingMode: "fixed",
    leadTimeLabel: "Next-day and scheduled slots.",
    startingPrice: 55,
    bookingFee: 15,
    basePrice: 46,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One small item", priceDelta: 0 },
      { value: "standard", label: "Large mirror or set of items", priceDelta: 24 },
      { value: "large", label: "Gallery wall or heavy mirror", priceDelta: 58 },
    ],
    addOns: [
      { value: "layout-planning", label: "Layout planning", amount: 16 },
      { value: "heavy-fixings", label: "Heavy-duty fixings", amount: 22 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "picture-hanging"],
  },
  {
    value: "shelf-curtain-fitting",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Shelf / curtain rail fitting",
    strapline: "Secure fitting for shelves, rails, and blinds in homes or offices.",
    bookingMode: "estimate",
    leadTimeLabel: "Scheduled fixture installation slots.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One fitting", priceDelta: 0 },
      { value: "standard", label: "Two to three fittings", priceDelta: 28 },
      { value: "large", label: "Multiple rooms", priceDelta: 70 },
    ],
    addOns: [
      { value: "provider-fixings", label: "Provider fixings pack", amount: 18 },
      { value: "ladder-work", label: "High ladder access", amount: 24 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "fixtures-fittings", "drilling"],
  },
  {
    value: "tap-toilet-seat-replacement",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Tap / toilet seat replacement",
    strapline: "Light plumbing fixture swaps without major pipework changes.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with photos of the current fitting.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Single simple replacement", priceDelta: 0 },
      { value: "standard", label: "One fitting with awkward access", priceDelta: 24 },
      { value: "large", label: "Multiple fixture swaps", priceDelta: 58 },
    ],
    addOns: [
      { value: "provider-parts-pickup", label: "Provider parts pickup", amount: 18 },
      { value: "old-fitting-disposal", label: "Old fitting disposal", amount: 12 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "light-plumbing"],
  },
  {
    value: "sealant-resealing",
    service: "handyman",
    subcategory: "repairs",
    label: "Sealant resealing",
    strapline: "Bathroom and kitchen silicone resealing and finish work.",
    bookingMode: "estimate",
    leadTimeLabel: "Photo-led quoting for baths, showers, and kitchen edges.",
    startingPrice: 59,
    bookingFee: 12,
    basePrice: 49,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "Single line reseal", priceDelta: 0 },
      { value: "standard", label: "Bath or shower perimeter", priceDelta: 20 },
      { value: "large", label: "Multiple bathroom / kitchen areas", priceDelta: 54 },
    ],
    addOns: [
      { value: "old-sealant-removal", label: "Full old sealant removal", amount: 18 },
      { value: "mould-treatment", label: "Mould treatment prep", amount: 14 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "resealing"],
  },
  {
    value: "minor-home-repairs",
    service: "handyman",
    subcategory: "repairs",
    label: "Minor home repairs",
    strapline: "General odd jobs, small repairs, and snagging visits.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with photos and a task list.",
    startingPrice: 85,
    bookingFee: 19,
    basePrice: 72,
    providerPayoutRatio: 0.68,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "One quick repair", priceDelta: 0 },
      { value: "standard", label: "Several small tasks", priceDelta: 34 },
      { value: "large", label: "Half-day snagging list", priceDelta: 88 },
    ],
    addOns: [
      { value: "materials-pickup", label: "Materials pickup", amount: 18 },
      { value: "sealant-finish", label: "Sealant finishing", amount: 20 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "minor-repairs"],
  },
  {
    value: "wardrobe-bed-assembly",
    service: "furniture-assembly",
    subcategory: "bedroom",
    label: "Wardrobe / bed assembly",
    strapline: "Assembly for flat-pack wardrobes, beds, and bedroom storage units.",
    bookingMode: "fixed",
    leadTimeLabel: "Bookable assembly slots with packaging options.",
    startingPrice: 89,
    bookingFee: 15,
    basePrice: 78,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Single bed or compact wardrobe", priceDelta: 0 },
      { value: "standard", label: "Double bed or medium wardrobe", priceDelta: 34 },
      { value: "large", label: "Large sliding wardrobe / ottoman bed", priceDelta: 92 },
    ],
    addOns: [
      { value: "wall-anchoring", label: "Wall anchoring", amount: 24 },
      { value: "packaging-removal", label: "Packaging removal", amount: 16 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "bedroom-furniture"],
  },
  {
    value: "desk-storage-assembly",
    service: "furniture-assembly",
    subcategory: "living-office",
    label: "Desk / storage assembly",
    strapline: "Assembly for desks, drawers, sideboards, and office storage.",
    bookingMode: "fixed",
    leadTimeLabel: "Bookable standard and extended assembly slots.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 59,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 2, large: 3.5 },
    sizeOptions: [
      { value: "small", label: "One desk or drawer unit", priceDelta: 0 },
      { value: "standard", label: "Large storage piece", priceDelta: 28 },
      { value: "large", label: "Multiple pieces", priceDelta: 74 },
    ],
    addOns: [
      { value: "wall-anchoring", label: "Wall anchoring", amount: 24 },
      { value: "room-placement", label: "Room positioning help", amount: 18 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "office-furniture"],
  },
  {
    value: "disassembly-reassembly",
    service: "furniture-assembly",
    subcategory: "extras",
    label: "Disassembly and reassembly",
    strapline: "Furniture take-down and rebuild for moves, storage, or room changes.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with item list and photos.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.66,
    durationHours: { small: 2, standard: 3, large: 5 },
    sizeOptions: [
      { value: "small", label: "One item", priceDelta: 0 },
      { value: "standard", label: "Bedroom set or two items", priceDelta: 42 },
      { value: "large", label: "Multiple large items", priceDelta: 108 },
    ],
    addOns: [
      { value: "repositioning", label: "Move between rooms", amount: 22 },
      { value: "packaging-removal", label: "Packaging / waste removal", amount: 16 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "disassembly"],
  },
  {
    value: "bagged-household-waste",
    service: "waste-removal",
    subcategory: "household",
    label: "Bagged household waste",
    strapline: "Loose bags, boxes, and standard household rubbish collection.",
    bookingMode: "estimate",
    leadTimeLabel: "Rapid booking with postcode and load-size pricing.",
    startingPrice: 79,
    bookingFee: 19,
    basePrice: 64,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Up to 6 bags", priceDelta: 0 },
      { value: "standard", label: "Half van load", priceDelta: 36 },
      { value: "large", label: "Full van load", priceDelta: 86 },
    ],
    addOns: [
      { value: "stairs-carry", label: "Upper-floor carry", amount: 22 },
      { value: "same-day-window", label: "Priority collection window", amount: 24 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "bagged-waste"],
  },
  {
    value: "bulky-item-removal",
    service: "waste-removal",
    subcategory: "bulky-items",
    label: "Bulky item removal",
    strapline: "Single or multiple bulky items such as sofas, mattresses, and white goods.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with clear item list and access notes.",
    startingPrice: 89,
    bookingFee: 19,
    basePrice: 74,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One bulky item", priceDelta: 0 },
      { value: "standard", label: "Two to three items", priceDelta: 42 },
      { value: "large", label: "Large bulky clearance", priceDelta: 98 },
    ],
    addOns: [
      { value: "heavy-items", label: "Heavy item handling", amount: 32 },
      { value: "two-person-lift", label: "Guaranteed two-person crew", amount: 28 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "bulky-items"],
  },
  {
    value: "property-clearance",
    service: "waste-removal",
    subcategory: "clearances",
    label: "Room / property clearance",
    strapline: "Clearances for rooms, garages, sheds, or end-of-tenancy waste loads.",
    bookingMode: "estimate",
    leadTimeLabel: "Often needs photos and may require manual review.",
    startingPrice: 129,
    bookingFee: 29,
    basePrice: 112,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 3, large: 5 },
    sizeOptions: [
      { value: "small", label: "Single room", priceDelta: 0 },
      { value: "standard", label: "Garage / shed / studio", priceDelta: 56 },
      { value: "large", label: "Large property clearance", priceDelta: 148 },
    ],
    addOns: [
      { value: "heavy-items", label: "Heavy item handling", amount: 32 },
      { value: "sweep-up", label: "Basic sweep-up finish", amount: 18 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "clearance"],
  },
  {
    value: "lawn-mowing",
    service: "garden-maintenance",
    subcategory: "routine",
    label: "Lawn mowing",
    strapline: "Routine grass cutting for front, back, or shared outdoor space.",
    bookingMode: "estimate",
    leadTimeLabel: "Scheduled garden maintenance slots.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Small garden", priceDelta: 0 },
      { value: "standard", label: "Medium garden", priceDelta: 24 },
      { value: "large", label: "Large garden or shared grounds", priceDelta: 62 },
    ],
    addOns: [
      { value: "green-waste", label: "Green waste removal", amount: 24 },
      { value: "edge-trim", label: "Edge trimming", amount: 18 },
    ],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "lawn-mowing"],
  },
  {
    value: "hedge-trimming",
    service: "garden-maintenance",
    subcategory: "cutting-trimming",
    label: "Hedge trimming",
    strapline: "Hedge and shrub trimming with tidy-down and waste options.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with height and access detail.",
    startingPrice: 79,
    bookingFee: 15,
    basePrice: 66,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Short hedge run", priceDelta: 0 },
      { value: "standard", label: "Standard perimeter hedge", priceDelta: 32 },
      { value: "large", label: "Tall or extensive hedge work", priceDelta: 82 },
    ],
    addOns: [
      { value: "green-waste", label: "Green waste removal", amount: 24 },
      { value: "ladder-access", label: "High ladder access", amount: 26 },
    ],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "hedge-trimming"],
  },
  {
    value: "garden-tidy-up",
    service: "garden-maintenance",
    subcategory: "seasonal",
    label: "Garden tidy-up",
    strapline: "Weeding, leaf clearance, light pruning, and general tidy-ups.",
    bookingMode: "estimate",
    leadTimeLabel: "Flexible booking with one-off and recurring options.",
    startingPrice: 75,
    bookingFee: 15,
    basePrice: 62,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Front or back tidy", priceDelta: 0 },
      { value: "standard", label: "Standard garden visit", priceDelta: 32 },
      { value: "large", label: "Large or overgrown tidy-up", priceDelta: 82 },
    ],
    addOns: [
      { value: "green-waste", label: "Green waste removal", amount: 24 },
      { value: "pressure-rinse", label: "Light pressure rinse", amount: 30 },
    ],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "tidy-up"],
  },
  {
    value: "deep-cleaning",
    service: "cleaning",
    subcategory: "home-cleaning",
    label: "Deep cleaning",
    strapline: "Thorough top-to-bottom cleaning for homes needing more than routine upkeep.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with room counts and condition level.",
    startingPrice: 96,
    bookingFee: 15,
    basePrice: 82,
    providerPayoutRatio: 0.67,
    durationHours: { small: 3, standard: 4.5, large: 6 },
    sizeOptions: [
      { value: "small", label: "Studio / 1 bed", priceDelta: 0 },
      { value: "standard", label: "2 to 3 bedroom home", priceDelta: 46 },
      { value: "large", label: "4 plus bedroom home", priceDelta: 104 },
    ],
    addOns: [
      { value: "inside-windows", label: "Inside windows", amount: 20 },
      { value: "appliance-clean", label: "Appliance clean", amount: 35 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "deep-cleaning"],
  },
  {
    value: "office-commercial-cleaning",
    service: "cleaning",
    subcategory: "tenancy-cleaning",
    label: "Office / commercial cleaning",
    strapline: "Scheduled or one-off commercial cleaning for small offices and shop floors.",
    bookingMode: "estimate",
    leadTimeLabel: "Commercial jobs may require manual review.",
    startingPrice: 85,
    bookingFee: 19,
    basePrice: 74,
    providerPayoutRatio: 0.68,
    durationHours: { small: 2, standard: 3.5, large: 6 },
    sizeOptions: [
      { value: "small", label: "Small office / shop", priceDelta: 0 },
      { value: "standard", label: "Medium premises", priceDelta: 48 },
      { value: "large", label: "Large floorplate", priceDelta: 120 },
    ],
    addOns: [
      { value: "washroom-restock", label: "Washroom restock", amount: 22 },
      { value: "out-of-hours", label: "Out-of-hours access", amount: 26 },
    ],
    propertyTypes: ["commercial"],
    providerTags: ["cleaning", "commercial-cleaning"],
  },
  {
    value: "airbnb-turnover-cleaning",
    service: "cleaning",
    subcategory: "tenancy-cleaning",
    label: "Airbnb turnover cleaning",
    strapline: "Turnover cleans with linen change and reset for short-let properties.",
    bookingMode: "estimate",
    leadTimeLabel: "Timed around check-out and check-in windows.",
    startingPrice: 72,
    bookingFee: 15,
    basePrice: 62,
    providerPayoutRatio: 0.68,
    durationHours: { small: 2, standard: 3, large: 4.5 },
    sizeOptions: [
      { value: "small", label: "Studio / 1 bed", priceDelta: 0 },
      { value: "standard", label: "2 to 3 bedroom short-let", priceDelta: 34 },
      { value: "large", label: "Large short-let property", priceDelta: 86 },
    ],
    addOns: [
      { value: "bed-linen-change", label: "Bed linen change", amount: 18 },
      { value: "consumables-reset", label: "Consumables reset", amount: 14 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "airbnb-turnover"],
  },
  {
    value: "after-builders-cleaning",
    service: "cleaning",
    subcategory: "tenancy-cleaning",
    label: "After-builders cleaning",
    strapline: "Dust, residue, and construction clean-down after works complete.",
    bookingMode: "estimate",
    leadTimeLabel: "Usually needs photos and condition review.",
    startingPrice: 145,
    bookingFee: 25,
    basePrice: 126,
    providerPayoutRatio: 0.67,
    durationHours: { small: 4, standard: 6, large: 8 },
    sizeOptions: [
      { value: "small", label: "Single room / minor works", priceDelta: 0 },
      { value: "standard", label: "Standard property clean-down", priceDelta: 72 },
      { value: "large", label: "Major renovation clean", priceDelta: 168 },
    ],
    addOns: [
      { value: "fine-dust-removal", label: "Fine dust removal", amount: 30 },
      { value: "window-detail", label: "Window detail clean", amount: 24 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["cleaning", "after-builders"],
  },
  {
    value: "sofa-upholstery-cleaning",
    service: "cleaning",
    subcategory: "specialist-cleaning",
    label: "Sofa / upholstery cleaning",
    strapline: "Fabric and upholstery refresh for sofas, armchairs, and soft furnishings.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked with item count and fabric detail.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Armchair or small sofa", priceDelta: 0 },
      { value: "standard", label: "Standard sofa set", priceDelta: 24 },
      { value: "large", label: "Large suite / multiple items", priceDelta: 62 },
    ],
    addOns: [
      { value: "stain-treatment", label: "Stain treatment", amount: 18 },
      { value: "deodorising", label: "Deodorising", amount: 12 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["cleaning", "upholstery-cleaning"],
  },
  {
    value: "oven-cleaning",
    service: "cleaning",
    subcategory: "appliance-cleaning",
    label: "Oven cleaning",
    strapline: "Single or double oven deep cleaning with rack and tray detailing.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple fixed-price appliance cleaning slot.",
    startingPrice: 55,
    bookingFee: 12,
    basePrice: 46,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Single oven", priceDelta: 0 },
      { value: "standard", label: "Double oven", priceDelta: 18 },
      { value: "large", label: "Range oven", priceDelta: 42 },
    ],
    addOns: [{ value: "hob-clean", label: "Hob clean", amount: 14 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "oven-cleaning"],
  },
  {
    value: "fridge-cleaning",
    service: "cleaning",
    subcategory: "appliance-cleaning",
    label: "Fridge cleaning",
    strapline: "Interior fridge or fridge-freezer cleaning and deodorising.",
    bookingMode: "fixed",
    leadTimeLabel: "Short fixed appliance cleaning slot.",
    startingPrice: 35,
    bookingFee: 10,
    basePrice: 28,
    providerPayoutRatio: 0.65,
    durationHours: { small: 0.75, standard: 1, large: 1.5 },
    sizeOptions: [
      { value: "small", label: "Under-counter fridge", priceDelta: 0 },
      { value: "standard", label: "Fridge-freezer", priceDelta: 10 },
      { value: "large", label: "American-style fridge", priceDelta: 24 },
    ],
    addOns: [{ value: "freezer-defrost", label: "Freezer defrost", amount: 12 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "fridge-cleaning"],
  },
  {
    value: "window-cleaning-interior",
    service: "cleaning",
    subcategory: "window-cleaning",
    label: "Window cleaning (interior)",
    strapline: "Interior glass and frame cleaning for accessible windows.",
    bookingMode: "estimate",
    leadTimeLabel: "Best combined with room count or window count.",
    startingPrice: 45,
    bookingFee: 12,
    basePrice: 36,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Up to 5 windows", priceDelta: 0 },
      { value: "standard", label: "6 to 10 windows", priceDelta: 18 },
      { value: "large", label: "Whole property interior", priceDelta: 46 },
    ],
    addOns: [{ value: "frame-detail", label: "Frame detail clean", amount: 12 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["cleaning", "interior-windows"],
  },
  {
    value: "window-cleaning-exterior-ground-floor",
    service: "cleaning",
    subcategory: "window-cleaning",
    label: "Window cleaning (exterior, ground floor only)",
    strapline: "Ground-floor exterior window cleaning with safe access only.",
    bookingMode: "estimate",
    leadTimeLabel: "Ground-floor only; upper windows need manual review.",
    startingPrice: 49,
    bookingFee: 12,
    basePrice: 40,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Front or back ground floor", priceDelta: 0 },
      { value: "standard", label: "Full ground floor property", priceDelta: 20 },
      { value: "large", label: "Large frontage / shopfront", priceDelta: 50 },
    ],
    addOns: [{ value: "frame-detail", label: "Frame detail clean", amount: 12 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["cleaning", "exterior-windows"],
  },
  {
    value: "bathroom-deep-clean",
    service: "cleaning",
    subcategory: "room-deep-cleans",
    label: "Bathroom deep clean",
    strapline: "Limescale, grout, glass, and fixture detailing for bathrooms.",
    bookingMode: "fixed",
    leadTimeLabel: "Short specialist room-clean slot.",
    startingPrice: 48,
    bookingFee: 10,
    basePrice: 40,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One bathroom", priceDelta: 0 },
      { value: "standard", label: "Large bathroom / en suite pair", priceDelta: 18 },
      { value: "large", label: "Multiple bathrooms", priceDelta: 46 },
    ],
    addOns: [{ value: "mould-treatment", label: "Mould treatment", amount: 15 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "bathroom-deep-clean"],
  },
  {
    value: "kitchen-deep-clean",
    service: "cleaning",
    subcategory: "room-deep-cleans",
    label: "Kitchen deep clean",
    strapline: "Grease, splashback, cupboard fronts, and worktop detailing.",
    bookingMode: "fixed",
    leadTimeLabel: "Kitchen-only deep clean with add-on appliances.",
    startingPrice: 65,
    bookingFee: 12,
    basePrice: 54,
    providerPayoutRatio: 0.66,
    durationHours: { small: 2, standard: 3, large: 4 },
    sizeOptions: [
      { value: "small", label: "Compact kitchen", priceDelta: 0 },
      { value: "standard", label: "Standard family kitchen", priceDelta: 24 },
      { value: "large", label: "Large kitchen / utility combo", priceDelta: 58 },
    ],
    addOns: [
      { value: "oven-clean", label: "Oven clean", amount: 20 },
      { value: "fridge-clean", label: "Fridge clean", amount: 15 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["cleaning", "kitchen-deep-clean"],
  },
  {
    value: "general-household-waste-removal",
    service: "waste-removal",
    subcategory: "household",
    label: "General household waste removal",
    strapline: "Mixed household bags, boxes, and small loose waste collection.",
    bookingMode: "estimate",
    leadTimeLabel: "Volume and access drive the final estimate.",
    startingPrice: 79,
    bookingFee: 19,
    basePrice: 64,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Up to 6 bags", priceDelta: 0 },
      { value: "standard", label: "Quarter to half van", priceDelta: 36 },
      { value: "large", label: "Full van equivalent", priceDelta: 86 },
    ],
    addOns: [
      { value: "stairs-carry", label: "Upper-floor carry", amount: 22 },
      { value: "dismantling", label: "Light dismantling", amount: 24 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "general-household"],
  },
  {
    value: "furniture-disposal",
    service: "waste-removal",
    subcategory: "bulky-items",
    label: "Furniture disposal",
    strapline: "Removal and disposal of sofas, wardrobes, tables, and similar items.",
    bookingMode: "estimate",
    leadTimeLabel: "Often depends on size, access, and dismantling needs.",
    startingPrice: 89,
    bookingFee: 19,
    basePrice: 74,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One item", priceDelta: 0 },
      { value: "standard", label: "Two to three items", priceDelta: 42 },
      { value: "large", label: "Room set / large suite", priceDelta: 98 },
    ],
    addOns: [
      { value: "dismantling", label: "Dismantling", amount: 24 },
      { value: "two-person-lift", label: "Two-person crew", amount: 28 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "furniture-disposal"],
  },
  {
    value: "mattress-removal",
    service: "waste-removal",
    subcategory: "special-disposal",
    label: "Mattress removal",
    strapline: "Single, double, or multiple mattress collections.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple per-item disposal pricing.",
    startingPrice: 45,
    bookingFee: 12,
    basePrice: 36,
    providerPayoutRatio: 0.65,
    durationHours: { small: 0.75, standard: 1, large: 1.5 },
    sizeOptions: [
      { value: "small", label: "One mattress", priceDelta: 0 },
      { value: "standard", label: "Two mattresses", priceDelta: 20 },
      { value: "large", label: "Three plus mattresses", priceDelta: 48 },
    ],
    addOns: [{ value: "stairs-carry", label: "Upper-floor carry", amount: 20 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "mattress-removal"],
  },
  {
    value: "appliance-removal",
    service: "waste-removal",
    subcategory: "special-disposal",
    label: "Appliance removal",
    strapline: "Removal of fridges, washing machines, and other large appliances.",
    bookingMode: "estimate",
    leadTimeLabel: "Appliance type and disposal rules affect final pricing.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One appliance", priceDelta: 0 },
      { value: "standard", label: "Two appliances", priceDelta: 28 },
      { value: "large", label: "Multiple appliances", priceDelta: 64 },
    ],
    addOns: [
      { value: "fridge-freezer-disposal", label: "Fridge / freezer disposal fee", amount: 25 },
      { value: "two-person-lift", label: "Two-person crew", amount: 28 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "appliance-removal"],
  },
  {
    value: "garage-shed-clearance",
    service: "waste-removal",
    subcategory: "clearances",
    label: "Garage / shed clearance",
    strapline: "Clearing stored items, rubbish, and general waste from external storage spaces.",
    bookingMode: "estimate",
    leadTimeLabel: "Usually needs photos and access details.",
    startingPrice: 119,
    bookingFee: 25,
    basePrice: 102,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 3.5, large: 5 },
    sizeOptions: [
      { value: "small", label: "Small shed", priceDelta: 0 },
      { value: "standard", label: "Standard garage", priceDelta: 56 },
      { value: "large", label: "Large packed garage / outbuilding", priceDelta: 138 },
    ],
    addOns: [
      { value: "heavy-items", label: "Heavy item handling", amount: 32 },
      { value: "sweep-up", label: "Basic sweep-up finish", amount: 18 },
    ],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "garage-clearance"],
  },
  {
    value: "office-clearance",
    service: "waste-removal",
    subcategory: "clearances",
    label: "Office clearance",
    strapline: "Desks, chairs, archive waste, and office clear-out jobs.",
    bookingMode: "estimate",
    leadTimeLabel: "Commercial access and timing may affect the quote.",
    startingPrice: 149,
    bookingFee: 29,
    basePrice: 128,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 4, large: 6 },
    sizeOptions: [
      { value: "small", label: "Small office", priceDelta: 0 },
      { value: "standard", label: "Medium office floor", priceDelta: 74 },
      { value: "large", label: "Large office clearance", priceDelta: 180 },
    ],
    addOns: [
      { value: "out-of-hours", label: "Out-of-hours access", amount: 30 },
      { value: "data-safe-pack", label: "Secure file / archive handling", amount: 24 },
    ],
    propertyTypes: ["commercial"],
    providerTags: ["waste-removal", "office-clearance"],
  },
  {
    value: "builders-waste-removal",
    service: "waste-removal",
    subcategory: "clearances",
    label: "Builders waste removal",
    strapline: "Rubble, bags, renovation debris, and post-works waste loads.",
    bookingMode: "estimate",
    leadTimeLabel: "Weight, access, and material type affect pricing.",
    startingPrice: 129,
    bookingFee: 25,
    basePrice: 112,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 3, large: 5 },
    sizeOptions: [
      { value: "small", label: "Few rubble bags", priceDelta: 0 },
      { value: "standard", label: "Quarter to half van", priceDelta: 56 },
      { value: "large", label: "Heavy full load", priceDelta: 148 },
    ],
    addOns: [
      { value: "heavy-items", label: "Heavy load handling", amount: 36 },
      { value: "stairs-carry", label: "Upper-floor carry", amount: 22 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["waste-removal", "builders-waste"],
  },
  {
    value: "mice-treatment",
    service: "pest-control",
    subcategory: "rodents",
    label: "Mice treatment",
    strapline: "Targeted mouse treatment with baiting and proofing notes.",
    bookingMode: "inspection",
    leadTimeLabel: "Priority domestic rodent treatment slots.",
    startingPrice: 119,
    bookingFee: 29,
    basePrice: 108,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Single room signs", priceDelta: 0 },
      { value: "standard", label: "Standard home treatment", priceDelta: 40 },
      { value: "large", label: "Large or repeat issue", priceDelta: 92 },
    ],
    addOns: [{ value: "proofing-note", label: "Proofing recommendations", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "mice-treatment"],
  },
  {
    value: "rat-treatment",
    service: "pest-control",
    subcategory: "rodents",
    label: "Rat treatment",
    strapline: "Rat treatment with baiting, proofing notes, and follow-up planning.",
    bookingMode: "inspection",
    leadTimeLabel: "Urgent rodent treatment coverage.",
    startingPrice: 139,
    bookingFee: 29,
    basePrice: 124,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2.5, large: 3.5 },
    sizeOptions: [
      { value: "small", label: "Single access point", priceDelta: 0 },
      { value: "standard", label: "Standard treatment", priceDelta: 46 },
      { value: "large", label: "Severe / repeated issue", priceDelta: 108 },
    ],
    addOns: [{ value: "proofing-note", label: "Proofing recommendations", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "rat-treatment"],
  },
  {
    value: "ant-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Ant treatment",
    strapline: "Targeted ant treatment for internal and external infestations.",
    bookingMode: "inspection",
    leadTimeLabel: "Fast insect treatment slots available.",
    startingPrice: 99,
    bookingFee: 25,
    basePrice: 88,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One treatment area", priceDelta: 0 },
      { value: "standard", label: "Multiple treatment points", priceDelta: 24 },
      { value: "large", label: "Large recurring issue", priceDelta: 62 },
    ],
    addOns: [{ value: "follow-up-visit", label: "Reserve follow-up visit", amount: 28 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "ant-treatment"],
  },
  {
    value: "flea-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Flea treatment",
    strapline: "Flea treatment with pet-safe planning and repeat visit options.",
    bookingMode: "inspection",
    leadTimeLabel: "Often requires room count and pet details.",
    startingPrice: 139,
    bookingFee: 29,
    basePrice: 122,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2.5, large: 3.5 },
    sizeOptions: [
      { value: "small", label: "Single room", priceDelta: 0 },
      { value: "standard", label: "Standard flat / house", priceDelta: 48 },
      { value: "large", label: "Whole property", priceDelta: 110 },
    ],
    addOns: [{ value: "follow-up-visit", label: "Reserve follow-up visit", amount: 35 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "flea-treatment"],
  },
  {
    value: "bed-bug-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Bed bug treatment",
    strapline: "Specialist bed bug treatment for bedrooms and furnished rooms.",
    bookingMode: "inspection",
    leadTimeLabel: "Usually requires manual review and room detail.",
    startingPrice: 179,
    bookingFee: 35,
    basePrice: 156,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 3, large: 4.5 },
    sizeOptions: [
      { value: "small", label: "One room", priceDelta: 0 },
      { value: "standard", label: "Two rooms", priceDelta: 68 },
      { value: "large", label: "Whole property", priceDelta: 168 },
    ],
    addOns: [{ value: "follow-up-visit", label: "Reserve follow-up visit", amount: 42 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "bed-bug-treatment"],
  },
  {
    value: "moth-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Moth treatment",
    strapline: "Moth treatment for wardrobes, carpets, and storage areas.",
    bookingMode: "inspection",
    leadTimeLabel: "Property size and affected areas affect the quote.",
    startingPrice: 109,
    bookingFee: 25,
    basePrice: 96,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One affected area", priceDelta: 0 },
      { value: "standard", label: "Multiple rooms", priceDelta: 34 },
      { value: "large", label: "Whole property", priceDelta: 86 },
    ],
    addOns: [{ value: "follow-up-visit", label: "Reserve follow-up visit", amount: 28 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "moth-treatment"],
  },
  {
    value: "silverfish-treatment",
    service: "pest-control",
    subcategory: "insects",
    label: "Silverfish treatment",
    strapline: "Moisture-area insect treatment for bathrooms, kitchens, and cupboards.",
    bookingMode: "inspection",
    leadTimeLabel: "Short specialist treatment slots.",
    startingPrice: 95,
    bookingFee: 25,
    basePrice: 84,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One affected area", priceDelta: 0 },
      { value: "standard", label: "Several rooms", priceDelta: 24 },
      { value: "large", label: "Whole property", priceDelta: 62 },
    ],
    addOns: [{ value: "follow-up-visit", label: "Reserve follow-up visit", amount: 28 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "silverfish-treatment"],
  },
  {
    value: "pigeon-proofing-inspection",
    service: "pest-control",
    subcategory: "proofing",
    label: "Pigeon proofing inspection",
    strapline: "Inspection visit for balconies, ledges, and roof-edge pigeon proofing needs.",
    bookingMode: "inspection",
    leadTimeLabel: "Inspection first; proofing quoted after survey.",
    startingPrice: 85,
    bookingFee: 25,
    basePrice: 72,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 2 },
    sizeOptions: [
      { value: "small", label: "Small balcony / ledge", priceDelta: 0 },
      { value: "standard", label: "Multiple ledges / roof line", priceDelta: 30 },
      { value: "large", label: "Large commercial frontage", priceDelta: 82 },
    ],
    addOns: [{ value: "written-report", label: "Written survey report", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "pigeon-proofing"],
  },
  {
    value: "proofing-sealing-entry-points",
    service: "pest-control",
    subcategory: "proofing",
    label: "Proofing / sealing entry points",
    strapline: "Sealing visible pest entry points after inspection or treatment.",
    bookingMode: "estimate",
    leadTimeLabel: "Best booked after inspection or with clear photos.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One to two points", priceDelta: 0 },
      { value: "standard", label: "Several entry points", priceDelta: 32 },
      { value: "large", label: "Extensive proofing work", priceDelta: 84 },
    ],
    addOns: [{ value: "materials-pack", label: "Proofing materials pack", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "proofing"],
  },
  {
    value: "pest-follow-up-visit",
    service: "pest-control",
    subcategory: "proofing",
    label: "Follow-up visit",
    strapline: "Return visit after treatment to inspect progress and repeat measures if needed.",
    bookingMode: "inspection",
    leadTimeLabel: "Follow-up slots after initial treatment.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 2 },
    sizeOptions: [
      { value: "small", label: "Standard follow-up", priceDelta: 0 },
      { value: "standard", label: "Extended revisit", priceDelta: 18 },
      { value: "large", label: "Large-site revisit", priceDelta: 46 },
    ],
    addOns: [{ value: "written-report", label: "Updated report", amount: 20 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["pest-control", "follow-up"],
  },
  {
    value: "weeding",
    service: "garden-maintenance",
    subcategory: "seasonal",
    label: "Weeding",
    strapline: "Bed, border, and paving weed removal for routine garden upkeep.",
    bookingMode: "estimate",
    leadTimeLabel: "Garden size and weed density affect duration.",
    startingPrice: 59,
    bookingFee: 12,
    basePrice: 48,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3.5 },
    sizeOptions: [
      { value: "small", label: "Small bed / path area", priceDelta: 0 },
      { value: "standard", label: "Standard garden beds", priceDelta: 26 },
      { value: "large", label: "Large or dense weeding", priceDelta: 68 },
    ],
    addOns: [{ value: "green-waste", label: "Green waste removal", amount: 24 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "weeding"],
  },
  {
    value: "leaf-clearance",
    service: "garden-maintenance",
    subcategory: "seasonal",
    label: "Leaf clearance",
    strapline: "Leaf gathering, bagging, and tidy-down for seasonal maintenance.",
    bookingMode: "estimate",
    leadTimeLabel: "Seasonal service with variable waste volume.",
    startingPrice: 55,
    bookingFee: 12,
    basePrice: 46,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "Small front or back", priceDelta: 0 },
      { value: "standard", label: "Standard garden", priceDelta: 22 },
      { value: "large", label: "Large heavy leaf fall", priceDelta: 58 },
    ],
    addOns: [{ value: "green-waste", label: "Green waste removal", amount: 24 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "leaf-clearance"],
  },
  {
    value: "pruning",
    service: "garden-maintenance",
    subcategory: "cutting-trimming",
    label: "Pruning",
    strapline: "Light shrub and plant pruning for shape and seasonal care.",
    bookingMode: "estimate",
    leadTimeLabel: "Plant type and reach affect final pricing.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3.5 },
    sizeOptions: [
      { value: "small", label: "Small planting area", priceDelta: 0 },
      { value: "standard", label: "Standard borders / shrubs", priceDelta: 28 },
      { value: "large", label: "Large planting areas", priceDelta: 70 },
    ],
    addOns: [{ value: "green-waste", label: "Green waste removal", amount: 24 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "pruning"],
  },
  {
    value: "small-tree-trimming",
    service: "garden-maintenance",
    subcategory: "cutting-trimming",
    label: "Small tree trimming",
    strapline: "Minor trimming for small garden trees and accessible branches.",
    bookingMode: "estimate",
    leadTimeLabel: "Height and access determine final quote.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "One small tree", priceDelta: 0 },
      { value: "standard", label: "Two trees / denser work", priceDelta: 38 },
      { value: "large", label: "Large trimming scope", priceDelta: 92 },
    ],
    addOns: [
      { value: "green-waste", label: "Green waste removal", amount: 24 },
      { value: "ladder-access", label: "Ladder access", amount: 26 },
    ],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "small-tree-trimming"],
  },
  {
    value: "garden-waste-bagging",
    service: "garden-maintenance",
    subcategory: "seasonal",
    label: "Garden waste bagging",
    strapline: "Bagging and staging green waste already cut or cleared on site.",
    bookingMode: "estimate",
    leadTimeLabel: "Volume and carry distance affect the quote.",
    startingPrice: 45,
    bookingFee: 12,
    basePrice: 36,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Small pile", priceDelta: 0 },
      { value: "standard", label: "Standard pile", priceDelta: 18 },
      { value: "large", label: "Large green waste load", priceDelta: 48 },
    ],
    addOns: [{ value: "green-waste", label: "Green waste removal", amount: 24 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "waste-bagging"],
  },
  {
    value: "pressure-washing-patio-driveway",
    service: "garden-maintenance",
    subcategory: "washing-finishing",
    label: "Pressure washing patio / driveway",
    strapline: "Pressure washing for patios, paths, and driveways with water access.",
    bookingMode: "estimate",
    leadTimeLabel: "Surface size and dirt level affect pricing.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Small patio / path", priceDelta: 0 },
      { value: "standard", label: "Standard patio or driveway", priceDelta: 42 },
      { value: "large", label: "Large exterior area", priceDelta: 102 },
    ],
    addOns: [{ value: "detergent-treatment", label: "Detergent treatment", amount: 16 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "pressure-washing"],
  },
  {
    value: "fence-painting",
    service: "garden-maintenance",
    subcategory: "washing-finishing",
    label: "Fence painting",
    strapline: "Fence refresh for small garden boundaries and panels.",
    bookingMode: "estimate",
    leadTimeLabel: "Panel count and paint supply affect final pricing.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 3.5, large: 5 },
    sizeOptions: [
      { value: "small", label: "Few panels", priceDelta: 0 },
      { value: "standard", label: "Standard perimeter", priceDelta: 46 },
      { value: "large", label: "Large boundary run", priceDelta: 114 },
    ],
    addOns: [{ value: "paint-supply", label: "Provider supplies paint", amount: 28 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "fence-painting"],
  },
  {
    value: "deck-cleaning",
    service: "garden-maintenance",
    subcategory: "washing-finishing",
    label: "Deck cleaning",
    strapline: "Cleaning and refreshing decking surfaces and steps.",
    bookingMode: "estimate",
    leadTimeLabel: "Deck size and dirt level affect the quote.",
    startingPrice: 85,
    bookingFee: 15,
    basePrice: 72,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Small deck area", priceDelta: 0 },
      { value: "standard", label: "Standard deck", priceDelta: 34 },
      { value: "large", label: "Large deck / steps", priceDelta: 86 },
    ],
    addOns: [{ value: "detergent-treatment", label: "Detergent treatment", amount: 16 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "deck-cleaning"],
  },
  {
    value: "seasonal-garden-maintenance",
    service: "garden-maintenance",
    subcategory: "seasonal",
    label: "Seasonal garden maintenance",
    strapline: "Combined seasonal tidy-up work for changing garden conditions.",
    bookingMode: "estimate",
    leadTimeLabel: "One-off or recurring seasonal visits available.",
    startingPrice: 89,
    bookingFee: 19,
    basePrice: 76,
    providerPayoutRatio: 0.67,
    durationHours: { small: 2, standard: 3, large: 5 },
    sizeOptions: [
      { value: "small", label: "Small seasonal visit", priceDelta: 0 },
      { value: "standard", label: "Standard maintenance round", priceDelta: 38 },
      { value: "large", label: "Large seasonal reset", priceDelta: 96 },
    ],
    addOns: [{ value: "green-waste", label: "Green waste removal", amount: 24 }],
    propertyTypes: ["terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["garden", "seasonal-maintenance"],
  },
  {
    value: "shelf-installation",
    service: "handyman",
    subcategory: "mounting-hanging",
    label: "Shelf installation",
    strapline: "Installation of one or more shelves on suitable wall surfaces.",
    bookingMode: "estimate",
    leadTimeLabel: "Wall type and shelf count affect the quote.",
    startingPrice: 59,
    bookingFee: 15,
    basePrice: 48,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One shelf", priceDelta: 0 },
      { value: "standard", label: "Two to three shelves", priceDelta: 22 },
      { value: "large", label: "Large / multiple walls", priceDelta: 58 },
    ],
    addOns: [{ value: "provider-fixings", label: "Provider fixings pack", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "shelf-installation"],
  },
  {
    value: "curtain-blind-installation",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Curtain / blind installation",
    strapline: "Installing curtain poles, rails, or blinds with drilling where needed.",
    bookingMode: "estimate",
    leadTimeLabel: "Window count and wall type affect the quote.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One window", priceDelta: 0 },
      { value: "standard", label: "Two to three windows", priceDelta: 28 },
      { value: "large", label: "Whole room / multiple rooms", priceDelta: 72 },
    ],
    addOns: [{ value: "provider-fixings", label: "Provider fixings pack", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "curtain-installation"],
  },
  {
    value: "furniture-moving-within-property",
    service: "handyman",
    subcategory: "moving-adjustments",
    label: "Furniture moving within property",
    strapline: "Internal room-to-room furniture moving without transport service.",
    bookingMode: "estimate",
    leadTimeLabel: "Crew size and awkward access affect pricing.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "One or two items", priceDelta: 0 },
      { value: "standard", label: "Several standard items", priceDelta: 28 },
      { value: "large", label: "Large / heavy move set", priceDelta: 74 },
    ],
    addOns: [{ value: "two-person-lift", label: "Two-person crew", amount: 28 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "internal-moving"],
  },
  {
    value: "door-handle-lock-replacement",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Door handle / lock replacement",
    strapline: "Replacing standard handles, latches, and non-emergency locks.",
    bookingMode: "estimate",
    leadTimeLabel: "Simple non-emergency lock and handle fitting.",
    startingPrice: 59,
    bookingFee: 15,
    basePrice: 48,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One replacement", priceDelta: 0 },
      { value: "standard", label: "Awkward fit / two items", priceDelta: 22 },
      { value: "large", label: "Multiple replacements", priceDelta: 52 },
    ],
    addOns: [{ value: "provider-parts-pickup", label: "Provider parts pickup", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "lock-replacement"],
  },
  {
    value: "minor-wall-repair-filling",
    service: "handyman",
    subcategory: "repairs",
    label: "Minor wall repair / filling",
    strapline: "Small holes, cracks, and patch repairs before repainting.",
    bookingMode: "estimate",
    leadTimeLabel: "Best priced with photos and patch count.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Few small holes", priceDelta: 0 },
      { value: "standard", label: "Several patches", priceDelta: 26 },
      { value: "large", label: "Large section repair", priceDelta: 64 },
    ],
    addOns: [{ value: "touch-up-paint", label: "Touch-up paint finish", amount: 22 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "wall-repair"],
  },
  {
    value: "flat-pack-adjustment",
    service: "handyman",
    subcategory: "moving-adjustments",
    label: "Flat-pack adjustment",
    strapline: "Tightening, realigning, and correcting assembled flat-pack furniture.",
    bookingMode: "estimate",
    leadTimeLabel: "Useful for snagging and loose-fix issues.",
    startingPrice: 55,
    bookingFee: 12,
    basePrice: 46,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One item", priceDelta: 0 },
      { value: "standard", label: "Two to three items", priceDelta: 22 },
      { value: "large", label: "Large multiple item adjustment", priceDelta: 54 },
    ],
    addOns: [{ value: "wall-anchoring", label: "Wall anchoring", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "flat-pack-adjustment"],
  },
  {
    value: "cabinet-fixing",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Cabinet fixing",
    strapline: "Minor cabinet securing and re-fixing work for kitchens and bathrooms.",
    bookingMode: "estimate",
    leadTimeLabel: "Photos help price cabinet condition and access.",
    startingPrice: 65,
    bookingFee: 15,
    basePrice: 54,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "One cabinet", priceDelta: 0 },
      { value: "standard", label: "Several cabinet points", priceDelta: 26 },
      { value: "large", label: "Multiple units", priceDelta: 62 },
    ],
    addOns: [{ value: "provider-fixings", label: "Provider fixings pack", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "cabinet-fixing"],
  },
  {
    value: "minor-plumbing-repair",
    service: "handyman",
    subcategory: "fixtures-fittings",
    label: "Minor plumbing repair",
    strapline: "Small visible plumbing fixes excluding major pipework or emergency leaks.",
    bookingMode: "estimate",
    leadTimeLabel: "Photo-led review recommended for plumbing jobs.",
    startingPrice: 79,
    bookingFee: 15,
    basePrice: 66,
    providerPayoutRatio: 0.67,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "Simple minor fix", priceDelta: 0 },
      { value: "standard", label: "Awkward access repair", priceDelta: 24 },
      { value: "large", label: "Multiple minor issues", priceDelta: 58 },
    ],
    addOns: [{ value: "provider-parts-pickup", label: "Provider parts pickup", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "minor-plumbing"],
  },
  {
    value: "light-fitting-replacement",
    service: "handyman",
    subcategory: "electrical-light",
    label: "Light fitting replacement",
    strapline: "Simple like-for-like light fitting swaps where allowed and safe.",
    bookingMode: "estimate",
    leadTimeLabel: "Non-complex fitting swaps only; regulated jobs need review.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.66,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One fitting", priceDelta: 0 },
      { value: "standard", label: "Two fittings", priceDelta: 22 },
      { value: "large", label: "Multiple fittings", priceDelta: 54 },
    ],
    addOns: [{ value: "ladder-work", label: "High ladder access", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "light-fitting"],
  },
  {
    value: "smoke-alarm-installation",
    service: "handyman",
    subcategory: "electrical-light",
    label: "Smoke alarm installation",
    strapline: "Battery or simple alarm fitting in accessible ceiling locations.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple fitting slots for standard smoke alarms.",
    startingPrice: 49,
    bookingFee: 12,
    basePrice: 40,
    providerPayoutRatio: 0.65,
    durationHours: { small: 0.75, standard: 1, large: 1.5 },
    sizeOptions: [
      { value: "small", label: "One alarm", priceDelta: 0 },
      { value: "standard", label: "Two alarms", priceDelta: 15 },
      { value: "large", label: "Three plus alarms", priceDelta: 38 },
    ],
    addOns: [{ value: "alarm-supply", label: "Provider supplies alarm", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "smoke-alarm"],
  },
  {
    value: "draft-excluder-sealing-work",
    service: "handyman",
    subcategory: "repairs",
    label: "Draft excluder / sealing work",
    strapline: "Simple draught-proofing and sealing work around doors and windows.",
    bookingMode: "estimate",
    leadTimeLabel: "Good for minor comfort and weatherproofing jobs.",
    startingPrice: 55,
    bookingFee: 12,
    basePrice: 46,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "One opening", priceDelta: 0 },
      { value: "standard", label: "Several openings", priceDelta: 20 },
      { value: "large", label: "Multiple rooms / property-wide", priceDelta: 52 },
    ],
    addOns: [{ value: "materials-pack", label: "Sealing materials pack", amount: 16 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["handyman", "draft-proofing"],
  },
  {
    value: "bed-assembly",
    service: "furniture-assembly",
    subcategory: "bedroom",
    label: "Bed assembly",
    strapline: "Standard single, double, ottoman, and similar bed assembly.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple item-based assembly slot.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 2, large: 3 },
    sizeOptions: [
      { value: "small", label: "Single / simple bed", priceDelta: 0 },
      { value: "standard", label: "Double / king bed", priceDelta: 24 },
      { value: "large", label: "Ottoman / bunk / complex bed", priceDelta: 62 },
    ],
    addOns: [{ value: "packaging-removal", label: "Packaging removal", amount: 16 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "bed-assembly"],
  },
  {
    value: "wardrobe-assembly",
    service: "furniture-assembly",
    subcategory: "bedroom",
    label: "Wardrobe assembly",
    strapline: "Assembly for freestanding wardrobes and storage units.",
    bookingMode: "fixed",
    leadTimeLabel: "Assembly pricing depends on size and door type.",
    startingPrice: 89,
    bookingFee: 15,
    basePrice: 78,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1.5, standard: 2.5, large: 4 },
    sizeOptions: [
      { value: "small", label: "Compact wardrobe", priceDelta: 0 },
      { value: "standard", label: "Standard wardrobe", priceDelta: 34 },
      { value: "large", label: "Large sliding wardrobe", priceDelta: 92 },
    ],
    addOns: [
      { value: "wall-anchoring", label: "Wall anchoring", amount: 24 },
      { value: "packaging-removal", label: "Packaging removal", amount: 16 },
    ],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "wardrobe-assembly"],
  },
  {
    value: "desk-assembly",
    service: "furniture-assembly",
    subcategory: "living-office",
    label: "Desk assembly",
    strapline: "Assembly for home office and study desks.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple desk and workstation assembly slot.",
    startingPrice: 59,
    bookingFee: 12,
    basePrice: 48,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Small desk", priceDelta: 0 },
      { value: "standard", label: "Standard workstation", priceDelta: 20 },
      { value: "large", label: "Large desk / corner desk", priceDelta: 52 },
    ],
    addOns: [{ value: "packaging-removal", label: "Packaging removal", amount: 16 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "desk-assembly"],
  },
  {
    value: "dining-table-assembly",
    service: "furniture-assembly",
    subcategory: "dining-seating",
    label: "Dining table assembly",
    strapline: "Assembly for dining tables and similar table sets.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple item or set-based assembly slot.",
    startingPrice: 65,
    bookingFee: 12,
    basePrice: 54,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 2.5 },
    sizeOptions: [
      { value: "small", label: "Small table", priceDelta: 0 },
      { value: "standard", label: "Standard table", priceDelta: 22 },
      { value: "large", label: "Extendable / complex table", priceDelta: 54 },
    ],
    addOns: [{ value: "chair-bundle", label: "Chair bundle add-on", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "dining-table-assembly"],
  },
  {
    value: "chair-assembly",
    service: "furniture-assembly",
    subcategory: "dining-seating",
    label: "Chair assembly",
    strapline: "Assembly for single chairs or chair sets.",
    bookingMode: "fixed",
    leadTimeLabel: "Quick per-item assembly slot.",
    startingPrice: 35,
    bookingFee: 10,
    basePrice: 28,
    providerPayoutRatio: 0.63,
    durationHours: { small: 0.75, standard: 1, large: 2 },
    sizeOptions: [
      { value: "small", label: "One chair", priceDelta: 0 },
      { value: "standard", label: "Two to four chairs", priceDelta: 16 },
      { value: "large", label: "Five plus chairs", priceDelta: 40 },
    ],
    addOns: [{ value: "packaging-removal", label: "Packaging removal", amount: 12 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "chair-assembly"],
  },
  {
    value: "chest-of-drawers-assembly",
    service: "furniture-assembly",
    subcategory: "bedroom",
    label: "Chest of drawers assembly",
    strapline: "Assembly for drawer units and bedroom storage pieces.",
    bookingMode: "fixed",
    leadTimeLabel: "Simple item-based assembly slot.",
    startingPrice: 59,
    bookingFee: 12,
    basePrice: 48,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "Small drawer unit", priceDelta: 0 },
      { value: "standard", label: "Standard chest", priceDelta: 20 },
      { value: "large", label: "Large unit / multiple drawers", priceDelta: 54 },
    ],
    addOns: [{ value: "wall-anchoring", label: "Wall anchoring", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "drawer-assembly"],
  },
  {
    value: "bookcase-assembly",
    service: "furniture-assembly",
    subcategory: "living-office",
    label: "Bookcase assembly",
    strapline: "Assembly for bookcases, shelving towers, and display storage.",
    bookingMode: "fixed",
    leadTimeLabel: "Quick item-based storage assembly slot.",
    startingPrice: 59,
    bookingFee: 12,
    basePrice: 48,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "Small bookcase", priceDelta: 0 },
      { value: "standard", label: "Standard bookcase", priceDelta: 20 },
      { value: "large", label: "Tall / multiple units", priceDelta: 54 },
    ],
    addOns: [{ value: "wall-anchoring", label: "Wall anchoring", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "bookcase-assembly"],
  },
  {
    value: "nursery-furniture-assembly",
    service: "furniture-assembly",
    subcategory: "special-ranges",
    label: "Nursery furniture assembly",
    strapline: "Assembly for cots, nursery drawers, and baby-room furniture.",
    bookingMode: "fixed",
    leadTimeLabel: "Careful assembly for nursery furniture items.",
    startingPrice: 69,
    bookingFee: 12,
    basePrice: 58,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 1.5, large: 3 },
    sizeOptions: [
      { value: "small", label: "One item", priceDelta: 0 },
      { value: "standard", label: "Two nursery items", priceDelta: 24 },
      { value: "large", label: "Full nursery setup", priceDelta: 60 },
    ],
    addOns: [{ value: "wall-anchoring", label: "Wall anchoring", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached"],
    providerTags: ["assembly", "nursery-assembly"],
  },
  {
    value: "ikea-assembly",
    service: "furniture-assembly",
    subcategory: "special-ranges",
    label: "IKEA assembly",
    strapline: "Model-specific IKEA assembly with product link or manual upload.",
    bookingMode: "estimate",
    leadTimeLabel: "Product link or model number improves accuracy.",
    startingPrice: 59,
    bookingFee: 15,
    basePrice: 48,
    providerPayoutRatio: 0.64,
    durationHours: { small: 1, standard: 2, large: 4 },
    sizeOptions: [
      { value: "small", label: "Simple IKEA item", priceDelta: 0 },
      { value: "standard", label: "Standard IKEA item", priceDelta: 24 },
      { value: "large", label: "Large / complex IKEA item", priceDelta: 68 },
    ],
    addOns: [{ value: "wall-anchoring", label: "Wall anchoring", amount: 24 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "ikea-assembly"],
  },
  {
    value: "multiple-item-assembly",
    service: "furniture-assembly",
    subcategory: "special-ranges",
    label: "Multiple item assembly",
    strapline: "Bundle pricing for multiple furniture items in one visit.",
    bookingMode: "estimate",
    leadTimeLabel: "Bundle estimate based on item count and complexity mix.",
    startingPrice: 95,
    bookingFee: 19,
    basePrice: 82,
    providerPayoutRatio: 0.66,
    durationHours: { small: 2, standard: 4, large: 6 },
    sizeOptions: [
      { value: "small", label: "Two items", priceDelta: 0 },
      { value: "standard", label: "Three to four items", priceDelta: 54 },
      { value: "large", label: "Five plus items", priceDelta: 140 },
    ],
    addOns: [{ value: "packaging-removal", label: "Packaging removal", amount: 16 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "multiple-item"],
  },
  {
    value: "disassembly",
    service: "furniture-assembly",
    subcategory: "extras",
    label: "Disassembly",
    strapline: "Taking down assembled furniture for moves or storage.",
    bookingMode: "estimate",
    leadTimeLabel: "Good with photos and item list.",
    startingPrice: 69,
    bookingFee: 15,
    basePrice: 58,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1, standard: 2, large: 4 },
    sizeOptions: [
      { value: "small", label: "One item", priceDelta: 0 },
      { value: "standard", label: "Two items", priceDelta: 28 },
      { value: "large", label: "Multiple large items", priceDelta: 84 },
    ],
    addOns: [{ value: "repositioning", label: "Move between rooms", amount: 22 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "disassembly"],
  },
  {
    value: "assembly-wall-fixing",
    service: "furniture-assembly",
    subcategory: "extras",
    label: "Assembly + wall fixing",
    strapline: "Assembly with anti-tip or wall securing included in one visit.",
    bookingMode: "estimate",
    leadTimeLabel: "Wall type and item size affect the final quote.",
    startingPrice: 89,
    bookingFee: 15,
    basePrice: 76,
    providerPayoutRatio: 0.65,
    durationHours: { small: 1.5, standard: 2.5, large: 4.5 },
    sizeOptions: [
      { value: "small", label: "One item with wall fixing", priceDelta: 0 },
      { value: "standard", label: "Standard wall-fixed item", priceDelta: 32 },
      { value: "large", label: "Large or multiple fixed items", priceDelta: 86 },
    ],
    addOns: [{ value: "provider-fixings", label: "Provider fixings pack", amount: 18 }],
    propertyTypes: ["flat", "terraced", "semi-detached", "detached", "commercial"],
    providerTags: ["assembly", "wall-fixing"],
  },
];

export const defaultService: ServiceValue = "handyman";
export const defaultJobTypeByService: Record<ServiceValue, string> = {
  cleaning: "regular-home-cleaning",
  "pest-control": "rat-mouse-treatment",
  handyman: "tv-mounting",
  "furniture-assembly": "wardrobe-bed-assembly",
  "waste-removal": "bagged-household-waste",
  "garden-maintenance": "lawn-mowing",
};

export function getServiceByValue(value: string | undefined) {
  return serviceCatalog.find((service) => service.value === value) ?? serviceCatalog.find((service) => service.value === defaultService)!;
}

export function getJobTypesByService(service: ServiceValue) {
  return jobTypeCatalog.filter((jobType) => jobType.service === service);
}

export function getJobTypeByValue(value: string | undefined, fallbackService?: ServiceValue) {
  if (value) {
    const exact = jobTypeCatalog.find((jobType) => jobType.value === value);
    if (exact) return exact;
  }

  const service = fallbackService ?? defaultService;
  return jobTypeCatalog.find((jobType) => jobType.value === defaultJobTypeByService[service])!;
}

export function getPropertyTypeOption(value: string | undefined) {
  return propertyTypeOptions.find((option) => option.value === value) ?? propertyTypeOptions[0];
}

export function getUrgencyOption(value: string | undefined) {
  return urgencyOptions.find((option) => option.value === value) ?? urgencyOptions[0];
}

export function getCleaningConditionOption(value: string | undefined) {
  return cleaningConditionOptions.find((option) => option.value === value) ?? cleaningConditionOptions[1];
}

export function getRecurringFrequencyOption(value: string | undefined) {
  return recurringFrequencyOptions.find((option) => option.value === value) ?? recurringFrequencyOptions[0];
}

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: 2,
  }).format(value);
}

export type QuoteInput = {
  service: ServiceValue;
  jobType: string;
  postcode: string;
  propertyType: PropertyTypeValue;
  jobSize: JobSizeValue;
  urgency: UrgencyValue;
  preferredDate: string;
  preferredTime: string;
  selectedAddOns: string[];
  bedrooms?: number;
  bathrooms?: number;
  kitchens?: number;
  areaSize?: number;
  cleaningCondition?: CleaningConditionValue;
  recurringFrequency?: RecurringFrequencyValue;
  visitCount?: number;
  suppliesProvidedBy?: "customer" | "provider";
};

export type QuoteBreakdown = {
  serviceLabel: string;
  jobTypeLabel: string;
  subcategory: string;
  coverage: CoverageResult;
  bookingMode: JobTypeDefinition["bookingMode"];
  estimatedDurationHours: number;
  bookingFee: number;
  basePrice: number;
  showJobSize: boolean;
  jobSizeAdjustment: number;
  scopeAdjustment: number;
  propertyAdjustment: number;
  urgencyAdjustment: number;
  timingAdjustment: number;
  postcodeAdjustment: number;
  addOnsTotal: number;
  subtotal: number;
  total: number;
  estimatedProviderPayout: number;
  estimatedPlatformMargin: number;
  providerTags: string[];
  visitCount: number;
};

function calculateTimingAdjustment(preferredDate: string, preferredTime: string) {
  if (!preferredDate) return 0;

  const bookingDate = new Date(`${preferredDate}T${preferredTime || "09:00"}:00`);
  if (Number.isNaN(bookingDate.getTime())) return 0;

  const day = bookingDate.getDay();
  const hour = Number((preferredTime || "09:00").split(":")[0] || "9");
  let total = 0;
  if (day === 0 || day === 6) total += 18;
  if (hour >= 18) total += 16;
  return total;
}

export function calculateQuote(input: QuoteInput): QuoteBreakdown {
  const service = getServiceByValue(input.service);
  const jobType = getJobTypeByValue(input.jobType, input.service);
  const sizeOption = jobType.sizeOptions.find((option) => option.value === input.jobSize) ?? jobType.sizeOptions[0];
  const propertyOption = getPropertyTypeOption(input.propertyType);
  const urgencyOption = getUrgencyOption(input.urgency);
  const coverage = getCoverageForPostcode(input.postcode);
  const visitCount = Math.max(input.visitCount ?? 1, 1);
  const isRoomCountCleaning = input.service === "cleaning" && ["home-cleaning", "tenancy-cleaning"].includes(jobType.subcategory);
  const addOnsTotal = jobType.addOns
    .filter((addOn) => input.selectedAddOns.includes(addOn.value))
    .reduce((sum, addOn) => sum + addOn.amount, 0);
  const timingAdjustment = calculateTimingAdjustment(input.preferredDate, input.preferredTime);
  const showJobSize = !(input.service === "cleaning" && isRoomCountCleaning);
  let jobSizeAdjustment = showJobSize ? sizeOption.priceDelta : 0;
  let estimatedDurationHours = jobType.durationHours[input.jobSize];
  let scopeAdjustment = 0;

  let subtotal =
    jobType.basePrice +
    jobSizeAdjustment +
    propertyOption.priceDelta +
    urgencyOption.priceDelta +
    coverage.priceAdjustment +
    timingAdjustment +
    addOnsTotal;

  if (isRoomCountCleaning) {
    const bedrooms = Math.max(input.bedrooms ?? 0, 0);
    const bathrooms = Math.max(input.bathrooms ?? 0, 0);
    const kitchens = Math.max(input.kitchens ?? 1, 1);
    const areaSize = Math.max(input.areaSize ?? 0, 0);
    const conditionOption = getCleaningConditionOption(input.cleaningCondition);
    const recurringOption = getRecurringFrequencyOption(input.recurringFrequency);
    const suppliesAdjustment = input.suppliesProvidedBy === "provider" ? 12 : 0;
    const baseVisitHours =
      0.8 +
      bedrooms * 0.95 +
      bathrooms * 0.55 +
      kitchens * 0.45 +
      (areaSize > 0 ? Math.max(0, areaSize - 650) / 500 : 0);
    estimatedDurationHours = Number((baseVisitHours * conditionOption.multiplier).toFixed(1));
    const hourlyRate =
      jobType.value === "regular-home-cleaning" ? 15 :
      jobType.value === "airbnb-turnover-cleaning" ? 16 :
      jobType.value === "office-commercial-cleaning" ? 17 :
      jobType.value === "deep-cleaning" ? 18 :
      jobType.value === "end-of-tenancy-cleaning" ? 20 :
      jobType.value === "after-builders-cleaning" ? 22 : 16;
    const perVisitCore = Number((estimatedDurationHours * hourlyRate).toFixed(2));
    scopeAdjustment = Number((perVisitCore - jobType.basePrice).toFixed(2));
    const singleVisitSubtotal = Number(((jobType.basePrice + scopeAdjustment + propertyOption.priceDelta + urgencyOption.priceDelta + coverage.priceAdjustment + timingAdjustment + addOnsTotal + suppliesAdjustment) * recurringOption.multiplier).toFixed(2));
    subtotal = Number((singleVisitSubtotal * visitCount).toFixed(2));
  } else if (input.service === "cleaning") {
    const suppliesAdjustment = input.suppliesProvidedBy === "provider" ? 12 : 0;
    scopeAdjustment = suppliesAdjustment;
    subtotal = Number((subtotal + suppliesAdjustment).toFixed(2));
  }

  const total = subtotal + jobType.bookingFee;
  const estimatedProviderPayout = Number((subtotal * jobType.providerPayoutRatio).toFixed(2));
  const estimatedPlatformMargin = Number((total - estimatedProviderPayout).toFixed(2));

  return {
    serviceLabel: service.label,
    jobTypeLabel: jobType.label,
    subcategory: jobType.subcategory,
    coverage,
    bookingMode: jobType.bookingMode,
    estimatedDurationHours,
    bookingFee: jobType.bookingFee,
    basePrice: jobType.basePrice,
    showJobSize,
    jobSizeAdjustment,
    scopeAdjustment,
    propertyAdjustment: propertyOption.priceDelta,
    urgencyAdjustment: urgencyOption.priceDelta,
    timingAdjustment,
    postcodeAdjustment: coverage.priceAdjustment,
    addOnsTotal,
    subtotal,
    total,
    estimatedProviderPayout,
    estimatedPlatformMargin,
    providerTags: jobType.providerTags,
    visitCount,
  };
}
