ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'PEST_CONTROL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'HANDYMAN';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'FURNITURE_ASSEMBLY';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'WASTE_REMOVAL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'GARDEN_MAINTENANCE';
